### ISSUE TITLE
As a user I would like to be able to install/uninstall multiple pims at a time

### ISSUE THREAD

**Issue by everettraven** [everettraven/packageless#50]
When running `packageless install` and `packageless uninstall` a user should be able to specify multiple pims at a time with a space separating each.

Examples:
`packageless install python dotnet git`

`packageless uninstall python dotnet git`

**Comment by felixlevert** [comment]
Could I give this a shot? New to Go so can't guarantee anything but I'll work on this tomorrow and see what I can do. Thanks!

**Comment by everettraven** [comment]
> Could I give this a shot? New to Go so can't guarantee anything but I'll work on this tomorrow and see what I can do. Thanks!

@felixlevert Sure thing! I will go ahead and assign the issue to you now.

If you have any questions, don't hesitate to ask!

**Comment by felixlevert** [comment]
Thanks! I'm taking a look now, and I think the easiest way to do this would be to modify the SubCommand helper function in subcommands/subcommand.go to loop through the args and call the Init and Run methods for each arg.

Doing it this way would enable this functionality for all subcommands, which as far as I can tell would be a desirable outcome? Please let me know if this is not the right approach.

If I do go with this approach, I think it would be best to modify all the subcommand's Init methods to take a string as argument instead of an array of strings like they currently do. I could always put each argument into a length 1 array before calling Init but this feels suboptimal. 

Lastly, as far as I can tell from reading the docs, I don't need to check for args past the subcommand that would be something other than a pim name? I don't see any options for flags or similar.

Thank you!

**Comment by everettraven** [comment]
@felixlevert

First of all, thanks so much for all the effort into coming up with a solution! I think the solution sounds great and I will review the PR as soon as I can.

You are also correct that the pim name is the only thing that should come after the sub commands as there is no other flags after them.

**Comment by everettraven** [comment]
closed with PR #55
